# Generated by Django 3.1.7 on 2021-03-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='conname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
