# Generated by Django 3.1.7 on 2021-03-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210315_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=100)),
                ('uname', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('pkey', models.CharField(blank=True, max_length=250, unique=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
