# Generated by Django 3.1.7 on 2021-03-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
